%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
# dataset_dir: /media/xiang/Data/Dataset/Kitti/dataset/sequences/00
dataset_dir: /home/ted/dev/tedvslam/data

# camera intrinsics
camera.fx: 458.654
camera.fy: 457.296
camera.cx: 367.215
camera.cy: 248.375

num_features: 150
num_features_init: 50
num_features_tracking: 50
